apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-manager.fullname" . }}
  labels:
    {{ include "s3-manager.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.targetPort | quote }}
  NODE_ENV: "production"
  LOCAL_DEV_MODE: {{ .Values.config.localDevMode | default false | quote }}
  WEB_ORIGIN: {{ .Values.config.webOrigin | quote }}
  OIDC_PROVIDER: {{ .Values.config.oidcProvider | quote }}
  AUTH_REQUIRED: {{ .Values.config.authRequired | quote }}
  DEFAULT_ROLE: {{ .Values.config.defaultRole | quote }}
  PIM_ENABLED: {{ .Values.config.pim.enabled | quote }}
  S3_ENDPOINT: {{ .Values.config.s3.endpoint | quote }}
  S3_REGION: {{ .Values.config.s3.region | quote }}
  S3_USE_SSL: {{ .Values.config.s3.useSSL | quote }}
  S3_VERIFY_SSL: {{ .Values.config.s3.verifySSL | quote }}
  SESSION_COOKIE_SECURE: {{ .Values.config.sessionCookieSecure | quote }}
  ROLE_PERMISSIONS: {{ .Values.config.rolePermissions | toJson | quote }}
