apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-manager.fullname" . }}
  labels:
    {{- include "s3-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.config.secretKey | quote }}
  AZURE_AD_TENANT_ID: {{ .Values.config.azureAd.tenantId | quote }}
  AZURE_AD_CLIENT_ID: {{ .Values.config.azureAd.clientId | quote }}
  AZURE_AD_CLIENT_SECRET: {{ .Values.config.azureAd.clientSecret | quote }}
{{- range $index, $source := .Values.config.s3.sources }}
  {{ printf "S3_SOURCE_%d_ACCESS_KEY" $index }}: {{ $source.accessKey | quote }}
  {{ printf "S3_SOURCE_%d_SECRET_KEY" $index }}: {{ $source.secretKey | quote }}
{{- end }}
