apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  # Rook-Ceph operator (reference external manifests)
  - https://raw.githubusercontent.com/rook/rook/release-1.19/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/release-1.19/deploy/examples/operator.yaml
  
  # Local cluster configuration
  - cluster.yaml
  - object-store.yaml
  - object-store-user.yaml
